### ISSUE TITLE
Using the style UKoLa leads to error "(\end occurred when \ifnum on line 22 was incomplete)"

### ISSUE THREAD

**Issue by maaattes** [komascript/uni-titlepage#2]
If I try to produce a titlepage using the MWE below, I see those entries in my logfile:
```console
…
(\end occurred when \ifnum on line 23 was incomplete)
(\end occurred when \if on line 23 was incomplete)
…
```
Output looks fine. I'm just wondering why these messages appear.
I'm using latest pdfTeX 3.141592653-2.6-1.40.23 (TeX Live 2021).

MWE:
```latex
\documentclass{scrartcl}
\usepackage[ngerman]{babel}
\usepackage{uni-titlepage}
\TitlePageStyle{UKoLa}

\begin{document}

\maketitle[%
  mainlogo={},
  secondlogo={},
  chair={},
  title={Ein schöner Titel},
  subject={Masterarbeit},
  academicgrade={Master of Science (M.\,Sc.)},
  discipline={Physik},
  author={Peter Pan},
  university={Musteruniversität},
  faculty={Fakultät für Physik},
  advisor={Prof. Dr. Karl-Heinz Meier},
  referee={Prof. Dr. Max Muster \and [f]Prof. Dr. Eva Muster},
  place={Musterhausen},
  date={Mai 2022}
]

\end{document}
```

**Comment by komascript** [comment]
Indeed a bug, that also occurs with the example file `titlepage-UKoLa.tex`. Unfortunately I seems, that it is not possible to make automatic `l3build` tests for such problems, without writing extra Lua code.

Thank you for the report. I will search for a fix as soon as possible. And maybe I can find a test method for this kind of bugs.
