### ISSUE TITLE
"! LaTeX Error: There's no line here to end." bei DHBW Stil

### ISSUE THREAD

**Issue by UweZiegenhagen** [komascript/uni-titlepage#5]
Das folgende Beispiel erzeugt einen Fehler:

! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.29 
     

```


\documentclass[12pt,ngerman]{scrreprt}
\usepackage{babel}
\usepackage{blindtext}
\usepackage{uni-titlepage}

\author{author}
\title{title}
\date{date}
\place{place}

\extratitle{extratitle}
\frontispiece{frontispiece}
\titlehead{titlehead}
\uppertitleback{uppertitleback}
\lowertitleback{lowertitleback}
\dedication{dedication}
\faculty{faculty}
\chair{chair}
\professor{professor}
\subject{subject}
\discipline{discipline}
\matriculationnumber{matriculationnumber}
\advisor{advisor}

\TitlePageStyle{DHBW}

\begin{document}
\maketitle

\blindtext[4]

\end{document}
```

**Comment by UweZiegenhagen** [comment]
Bei Nutzung von TU-HH gibt es den gleichen Fehler.

**Comment by komascript** [comment]
> Following example result in error:
>
> ! LaTeX Error: There's no line here to end.

Once more a documentation lack, that has to be fixed:

Some styles have mandatory options. Here `academicgrade` is missing. An empty academic grade does not make sense for this title style because of the line »für die Prüfung zum«.

**Comment by komascript** [comment]
I've changed the code to report a better error and added a note below the table of all options:

> Note: Depending on the used style some elements are mandatory. You will get
an error message like  
`Package uni-titlepage Error: empty title element ‘author’.`  
if such a mandatory element has not been set. In this case use either the
option or the corresponding command to setup at least a dummy value, e.g.  
`\author{DON’T FORGET TO CHANGE THE AUTHOR}`  
before the corresponding `\maketitle`.

Is this OK for you?

You can test it, if you would [download the current source and do a local installation](https://github.com/komascript/uni-titlepage#unpacking-and-installation-for-developers-and-distributors).

**Comment by UweZiegenhagen** [comment]
That is fine for me.
